# Generated by Django 3.2.16 on 2023-12-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('employer_logo', models.URLField(blank=True, null=True)),
                ('employer_website', models.URLField(blank=True, null=True)),
                ('employer_company_type', models.CharField(blank=True, max_length=200, null=True)),
                ('job_publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('job_id', models.CharField(blank=True, max_length=200, null=True)),
                ('job_employment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('job_apply_link', models.URLField(blank=True, null=True)),
                ('apply_options', models.JSONField(blank=True, max_length=200, null=True)),
                ('job_apply_is_direct', models.BooleanField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_is_remote', models.BooleanField(blank=True, null=True)),
                ('job_posted_at_timestamp', models.DateTimeField(blank=True, max_length=30, null=True)),
                ('job_posted_at_datetime_utc', models.DateTimeField(blank=True, max_length=30, null=True)),
                ('job_city', models.CharField(blank=True, max_length=200, null=True)),
                ('job_state', models.CharField(blank=True, max_length=200, null=True)),
                ('job_country', models.CharField(blank=True, max_length=200, null=True)),
                ('job_benefits', models.CharField(blank=True, max_length=2000, null=True)),
                ('job_google_link', models.URLField(blank=True, null=True)),
                ('job_offer_expiration_datetime_utc', models.DateTimeField(blank=True, max_length=30, null=True)),
                ('job_offer_expiration_timestamp', models.IntegerField(blank=True, null=True)),
                ('job_required_skills', models.TextField(blank=True, max_length=2000, null=True)),
                ('job_experience_in_place_of_education', models.BooleanField(blank=True, null=True)),
                ('job_min_salary', models.FloatField(blank=True, max_length=30, null=True)),
                ('job_max_salary', models.FloatField(blank=True, max_length=30, null=True)),
                ('job_salary_currency', models.CharField(blank=True, max_length=200, null=True)),
                ('job_salary_period', models.CharField(blank=True, max_length=200, null=True)),
                ('job_posting_language', models.CharField(blank=True, max_length=5, null=True)),
                ('job_required_experience', models.JSONField(blank=True, null=True)),
                ('job_required_education', models.JSONField(blank=True, null=True)),
                ('job_highlights', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
