# Generated by Django 3.2.16 on 2023-12-24 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_offer_expiration_timestamp',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_posted_at_timestamp',
        ),
    ]
