# Generated by Django 3.2.16 on 2023-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20231229_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_required_education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_required_experience',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
