# Generated by Django 5.0.1 on 2024-01-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_auto_20231229_1228"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="employer_company_type",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="employer_logo",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="employer_name",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="employer_website",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_publisher",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
